tt

diff --git a/.github/workflows/docker-build-ci.yml b/.github/workflows/docker-build-ci.yml
--- a/.github/workflows/docker-build-ci.yml
+++ b/.github/workflows/docker-build-ci.yml
@@ -18,4 +18,5 @@ jobs:
           sudo apt-get install make
       - shell: bash
         run: |
+          run: test -f docker_build || { echo "Makefile not found"; exit 1; }
           make docker_build
